language: python
os:
  - linux
addons:
  chrome: stable
python:
  - "3.6"
install:
  - make env.up
before_script:
  - make serve &
  - sleep 5
script:
  - make ci
after_script:
  - pkill "make serve"
  - python deploy.py
