theme: jekyll-theme-cayman
title: vue.py
description: Pythonic Vue.js
include:
  - __init__.py
  - _js
navigation:
  - title: Start
    link: /
  - title: Documentation
    link: docs
  - title: Gallery
    link: examples
